### ISSUE TITLE
Investigate using Actions for continuous integration tools

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#1]
Investigate using GitHub Actions for continuous integration, answering the following: 
1. Are there privacy, licensing concerns that may prevent us from using the tool?
1. Is the tool free?
1. How difficult is it to use the tool?
1. Does the tool provide useful "badges", reports, that present data such as code coverage and quality?

If the above can be answered positively, create another task to integrate the tool (if needed, may not be if the tool is easy to set up).

**Comment by mansiPaTeLL** [comment]
1. Jenkins/Travis CI

> 1. Are there privacy, licensing concerns that may prevent us from using the tool? There are no privacy concerns or licensing
> 2. Is the tool free? Yes, it is free, we do not need to pay anything. 
> 3. How difficult is it to use the tool? It is easy to use and configure. 
> 4. Does the tool provide useful "badges", reports, that present data such as code coverage and quality? This tool provides useful badges, reports etc. 

2. Circle CI - 

> 1. Are there privacy, licensing concerns that may prevent us from using the tool? No concern regarding this
> 2. Is the tool free? No, it is not free
> 3. How difficult is it to use the tool? It is easy to use and configure 
> 4. Does the tool provide useful "badges", reports, that present data such as code coverage and quality? Yes it does provides badges and reports. 

Note: We will discuss which one we should use, and then will set it and configure it.
