### ISSUE TITLE
Define the unit/integration/system test workflows 

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#100]
This task is done when we've defined a workflow/approach to writing code tests in Flutter that tells developers how to:
1. start writing tests
2. what they should consider when writing tests for the first time
3. and links to good TDD information to keep in mind when writing tests

This is especially important to help developers identify test cases "on the fly" for individual classes/widgets that aren't defined by system test procedure.

**Comment by holtzmak** [comment]
@MummenRider , @SanaKhan1997 added the wiki page [Testing Workflow](https://github.com/holtzmak/Humane-Transport/wiki/Testing-Workflow). Let me know if you think something is missing.

**Comment by MummenRider** [comment]
A really detailed wiki page, LGTM!

**Comment by mansiPaTeLL** [comment]
@holtzmak I also reviewed it and it LGTM.

**Comment by SanaKhan1997** [comment]
Looks good! thank you
