### ISSUE TITLE
Begin investigating and writing up system test procedures

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#101]
Follow-up to #100.

In this task you will:
- [x] Identify and document the system-level tests for our application, using a combination of existing documentation and foresight for them
- [x] have these procedures double-checked by the project mentor(s) for quality assurance
- [x] also define the system test procedure documentation format (wiki page)

This task does not involve programming the test procedures.

**Comment by holtzmak** [comment]
Thinking about validation (ensuring we do what client needs) system tests: 
1. we used user story/journey maps to define how transporter's act in different situations, we should use these to determine what the application should provide, if anything (in parallel to how the transporter would act)
1. we should then write our system tests in a similar format, but on the wiki so that we can revise them readily and mark completed tests with ✅ .

> I would describe further the above tests as instructing the test driver to do x, y, z and then verify at the end some message occurs (or doesn't!) and that changes were made to databases as expected

Thinking about verification (ensuring we do what we set out in requirements) system tests... I think we should be considering system performance in such tests:
1. every class/widget should do the work we told it to do when we tell it, and should not behave unexpectedly (meaning we fix bugs we find in system tests so the class does what it should do and not what we originally thought it should do)
1. we need to consider mobile device performance with all our software instructions. A neat article I read on this was "[How to take a systems approach to mobile app testing](https://techbeacon.com/app-dev-testing/how-take-systems-approach-mobile-app-testing)" - which if you read it, suggests common sense, but is important nonetheless.
1. perhaps the above point suggests manual testing, or at least running the automated tests on a real device to ensure it doesn't explode :)

> Then, I would describe further the above tests as checking that our internal classes/widgets did their work as promised by their interface, and that the right thing occurring in validation wasn't the result of a bug in verification that had the same result.
>
> So, we should do both validation and verification in the same programmed test case!

**Comment by holtzmak** [comment]
@SanaKhan1997 , @MummenRider Started the first system test cases [here](https://github.com/holtzmak/Humane-Transport/wiki/Animal-Transport-Record-System-Test-Procedures). What do you think of this structure? Are the cases described well?

There will be more - following of structure of wide (many tests) but shallow (short tests).

**Comment by mansiPaTeLL** [comment]
@holtzmak The structure is well defined. We can also things what can happens during test and when it can happens in just one sentence. I do believe we should consider device capability and other things you have mentioned. The article you have pointed out is very useful. I was just reviewing the test structure so thought to add comment on it. Thanks.

**Comment by SanaKhan1997** [comment]
Really like it! except I was thinking if we should think about local storage management and have some tests to ensure old ATR forms(or perhaps ones that are saved in remote) should be deleted from local.

**Comment by holtzmak** [comment]
> Really like it! except I was thinking if we should think about local storage management and have some tests to ensure old ATR forms(or perhaps ones that are saved in remote) should be deleted from local.

If I recall, we'll want some finished ATR forms in local as a way of caching. I'll be sure to add a test for when the cache is as full as we want it to be, and a new form is saved, thus kicking out the oldest form from the cache (local database).

**Comment by holtzmak** [comment]
@SanaKhan1997 @MummenRider Tentatively completed the ATR-related test cases [here](https://github.com/holtzmak/Humane-Transport/wiki/Animal-Transport-Record-Related-System-Test-Procedures). Are there any additional cases you can think of? **Please see the disclaimer on what content is included in system tests the given link** (we ignore super specific test cases like going back to fill out contingency plan halfway through the ATR - these are better suited to smaller unit or integration tests).

I will write up system tests for other topics including:
- [x] Transporter Accounts (tests including account classes and databases)
- [x] System Settings (tests including app code and underlying OS)

What additional, separate system interactions can you think of? I used the client-server architecture model to see how each persona interacts with the app and what systems an interaction would involve.

> We could add additional, highly specific system tests for the cases we have in the UJMs, like: "An animal is injured in transport, and we address the animal according to contingency plan".
>
> But ultimately, the Transporter's interaction with the app in such an extreme case is still to just open the app and either change what they've written in the in-progress ATR or add new text to it.
>
> The UJMs then influence what we offer in design, but as for test cases, we could test the above simply in a unit test (or integration test) by starting an ATR, saving it, then going back in to edit it. It shouldn't matter which fields we're changing in any case as long as something is changed.

**Comment by MummenRider** [comment]
For this category: Generic ATR management actions (no focus on ATR content), how about adding the system interaction where user updates his/ her personal information (e.g. Updates address/ name). Other than that, I believe you covered most cases

**Comment by holtzmak** [comment]
> For this category: Generic ATR management actions (no focus on ATR content), how about adding the system interaction where user updates his/ her personal information (e.g. Updates address/ name). Other than that, I believe you covered most cases

Are you referring to editing an ATR field or Transporter account information? Are you thinking that account information should be used to populate the ATR?

**Comment by MummenRider** [comment]
@holtzmak , I was referring to user's information.

**Comment by holtzmak** [comment]
@MummenRider , @SanaKhan1997 Semi-final call for review on the test cases. I've added cases for [Transporter accounts](https://github.com/holtzmak/Humane-Transport/wiki/Transporter-Account-Related-System-Test-Procedures) and [Shared settings](https://github.com/holtzmak/Humane-Transport/wiki/System-Settings-Related-System-Test-Procedures) (not a lot of these, as other tests for themes and so on will be added when we go to add extra things). What do you think?

I will run these tests by our project mentor yet, so maybe one more review after that.

**Comment by mansiPaTeLL** [comment]
@holtzmak After entering all the information in ATR, a transporter needs to verify all the information. At the end transporter must open the document to verify and need to confirm that all information is correct or not. Only then he/she can submit the document. We can have test case for this scenario as well.

**Comment by holtzmak** [comment]
> @holtzmak After entering all the information in ATR...

@mansiPaTeLL Just curious, would this be a read-only version of the ATR as if it were being edited, or would this be a PDF of the ATR?

**Comment by mansiPaTeLL** [comment]
> > @holtzmak After entering all the information in ATR...
> 
> @mansiPaTeLL Just curious, would this be a read-only version of the ATR as if it were being edited, or would this be a PDF of the ATR?

After completing all the section, at the end when transporter click on submit, the system should bring read-only version because he/she has to check all the details and if he wants to edit something he should be able go back and edit before submitting ATR form. After he verifies and submit a ATR, the ATR will become read-only version and won't able to edit. If transporter wants the PDF version to print or to share, he can click on "generate pdf version" option.

**Comment by holtzmak** [comment]
@mansiPaTeLL  add the test case "Successfully cancelling ATR save does not contact remote, retries" to [ATR-related test cases](https://github.com/holtzmak/Humane-Transport/wiki/Animal-Transport-Record-Related-System-Test-Procedures).

**Comment by holtzmak** [comment]
Received feedback from project mentor: the tests are good to go. He suggested a visual aid with the tests would help us continue to be thorough:
- [x] Add state diagram to each set of procedures to aid understanding
