### ISSUE TITLE
No drawer icon showing on Android devices

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#121]
Ignoring my teeny tiny device, there's no obvious evidence of the drawer on Android devices. I think the fix for this is to make an icon to share between iOS and Android.

https://user-images.githubusercontent.com/32527219/105563766-efc69580-5ce4-11eb-850c-873004241856.mov

**Comment by MummenRider** [comment]
What kind of device is this? I tried this on my android emulator and worked perfectly. Possible solution to this is to create our own custom AppBar widget and make sure it's under Safe Area Widget

**Comment by holtzmak** [comment]
@MummenRider says in video, top left, Google Pixel 3XL.

**Comment by MummenRider** [comment]
Emulated the exact device shown on the video and worked perfectly. Weird that happened to you

**Comment by holtzmak** [comment]
It's likely I was in a bad state, I refreshed/restarted my AVD using latest on master and could not recreate the problem. This bug no longer/doesn't exist.
