### ISSUE TITLE
Structure Firebase Database ATR Documents

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#124]
Structure the Firebase Database as per database architecture documentation:
- [x] Structure ATR data

You may find the guide to [Structuring your Firebase Database](https://firebase.google.com/docs/database/web/structure-data) to be useful. It also includes some tips on making our data scaleable.

**Comment by holtzmak** [comment]
@mansiPaTeLL the ATR documents should have an ID that matches that of the account who made the ATR. See also #151 .

**Comment by mansiPaTeLL** [comment]
@MummenRider @SanaKhan1997 @holtzmak  Please review it in Firestore Console

**Comment by holtzmak** [comment]
@holtzmak Looks good! As discussed in scrum, could you add a field `isComplete: bool` that we can use later with query rules to prevent incomplete records from being in the database?

**Comment by mansiPaTeLL** [comment]
> @holtzmak Looks good! As discussed in scrum, could you add a field `isComplete: bool` that we can use later with query rules to prevent incomplete records from being in the database?

I added this. Closing this issue.

**Comment by mansiPaTeLL** [comment]
Added `isComplete:bool` in firestore database structure.
