### ISSUE TITLE
Set the Firebase Database ATR Query rules

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#125]
Blocked by #124 and #151.

First consider [understanding the firebase realtime database rules](https://firebase.google.com/docs/database/security). Important things to be mindful of include:
1. Limiting authorization (i.e. a transporter should not be able to ask or use other transporter data)
2. Enforcing a query structure (i.e. what a valid query looks like)
3. investigate the internet for other community-recommended rules

In this task, you should write rules for: 

- [x] Limiting which records can be fetched, where transporters may only get ATRs that have their ID
- [x] Limiting number of records fetched at a time, so only fetch latest 10 records matching the query
- We should also have a version of the function that will grab all records matching (it will be used less often, but still used)

*IMPORTANT*: Obviously don't share here what the rules are, for review this task must be addressed through our Firebase Console.

**Comment by holtzmak** [comment]
Consider also the Admin status of accounts: only the person who made the ATR or admin can read (fetch) ATRs.

Admins don't have write access for any reason.

**Comment by SanaKhan1997** [comment]
When implementing firebase interface things we need to clear all security rules

1.  When signing up, isAdmin field must be filled out with either true or false. Rules will allow user to write and read their own document or if isAdmin == true, read will be allowed for every document in atr collection
2. When submitting or saving atr document, their must be a field of completeStatus and userId(this can be fetched for user collection i.e this will not be submitted by users but fetched from firestore via database interface)

**Comment by SanaKhan1997** [comment]
Helpful links with examples:

1. [Basic Rules](https://fireship.io/snippets/firestore-rules-recipes/)
2. [Role Based Access](https://fireship.io/lessons/role-based-authorization-with-firestore-nosql-and-angular-5/)
3. [Rules with constraints](https://firebase.google.com/docs/firestore/security/rules-query)

**Comment by holtzmak** [comment]
@SanaKhan1997 . I've reviewed the rules so far. LGTM!

One thing: why do we check the request time?
`request.time < timestamp.date(2021, 3, 1)`?

**Comment by SanaKhan1997** [comment]
> @SanaKhan1997 . I've reviewed the rules so far. LGTM!
> 
> One thing: why do we check the request time?
> `request.time < timestamp.date(2021, 3, 1)`?
Removed it since we dont need it. This was done during initial setup by Clark.
