### ISSUE TITLE
Refactor Mid-Fi GUI Prototypes according to early feedback

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#126]
We've received some feedback so far on the mid-fi prototypes [here](https://docs.google.com/forms/d/1zewHB-Q56wqB6F_v30-xZvLieB0swqi-t3zOTAjCa40/edit#responses).

A major issue so far is that we did not take the time to make the prototype fully interact-able, because we did not foresee that we needed to expend such effort. For this task:

- [x] Update the mid-fis to satisfy the feedback we've received, and make it obvious what the limitations are/where we were lazy

_(i.e. add discoverability to things like the burger menu, like a tooltip that says it would be on every screen but is not in the prototype)_

- [x] Forward the updated mid-fis to our client to ensure the updated prototypes are the ones reviewed

We don't want to end up with a bunch of feedback that says something along the lines of "I couldn't do this because the prototype didn't have all the links, was missing the menu on every screen, etc." because we didn't make obvious the limitations of the prototype.

**Comment by mansiPaTeLL** [comment]
New/Updated Version of Design Links - 
Design#1 - [https://xd.adobe.com/view/9c2642bc-9484-44ed-a6e1-3fa065fcfcbd-c975/](https://xd.adobe.com/view/9c2642bc-9484-44ed-a6e1-3fa065fcfcbd-c975/)
Design#2 - [https://xd.adobe.com/view/9a6f1910-d3ac-4fdf-b051-c2c78510ba32-cf3c/](https://xd.adobe.com/view/9a6f1910-d3ac-4fdf-b051-c2c78510ba32-cf3c/)

@holtzmak @MummenRider @SanaKhan1997 Please review these updated version of our designs. 

We do not need to send links to our users. I confirmed that it automatically updates the prototypes.

**Comment by holtzmak** [comment]
Both designs look good to me, I appreciate the tooltips very much. What does confuse me though is that the history records aren't clickable.
- [x] Could you either add a tool tip that says the history record will look like the in-progress record, or add an example history record display screen?

**Comment by mansiPaTeLL** [comment]
@holtzmak Added History record screen in Design 2 and added tool tip in design 1.
