### ISSUE TITLE
Investigate local "rules" for Firebase Database

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#127]
The local database has some particular design rules we wish to enforce, including:
1. to not push updated to the remote database when the ATR is not marked complete
2. to limit the number of records on the phone
3. to pull in more records temporarily on the phone when searching through ATR history

You can see the full extent of what the local database should do in the system tests for ATRs.

- [x] Investigate if we can manage the local firebase database to do what we want, or if we are forced to use it the way Google wants

If this is not possible, determine what we should do if anything, and update and documentation/system tests accordingly.

**Comment by SanaKhan1997** [comment]
We can write our customized functions in firestore security rules to ensure ATR is not pushed if incomplete--[see this](https://firebase.google.com/docs/firestore/security/rules-conditions#custom_functions). Also if we overwrite a completed ATR when offline by default firestore will allow to cache it but once network comes back on these cache will send validation request to firestore. If it fails the validation cache will be restored with previous record(original).

**Comment by holtzmak** [comment]
> We can write our customized functions in firestore security rules to ensure ATR is not pushed if incomplete--see this. 

Thanks for finding this! I think this will indeed cover our use cases of:
* Only getting records made by the transporter for the transporter (if we add user ID to the documents or something)
* Preventing write access to complete records (I think this the point you made: ` If it fails the validation cache will be restored with previous record(original).`

So... I have some questions (that you may have answered already): 
1. Are the rules for preventing incomplete (not saved as complete) records in Firestore rules or would we have to write code on the device to precent that?
2. Can we have multiple query functions, like one with limited records returned and one with more records returned?

**Comment by SanaKhan1997** [comment]
1. Are the rules for preventing incomplete (not saved as complete) records in Firestore rules or would we have to write code on the device to precent that?

> Firebase does allow data validation for write and update queries using (request.resource). We will have to decide appropriate data validation conditions for firebase such as, if any acknowledgment is missing mark document as incomplete. See [example 2 in Data Validation Section](https://firebase.google.com/docs/firestore/security/rules-conditions#data_validation)

2. Can we have multiple query functions, like one with limited records returned and one with more records returned?

> Yes! this is done by limiting the number of records we wish to retrieve. By default firestore will retrieve all the documents satisfying query but adding .limit(number) will return only certain records. Check out this guide for using [limits and order](https://firebase.google.com/docs/firestore/query-data/order-limit-data)

3. To limit the number of records on phone:

> We can use cache configuration for this purpose. By default cache size is 40 MB but we can change this by using [setPersistanceCacheSizeByte](https://firebase.google.com/docs/reference/android/com/google/firebase/database/FirebaseDatabase#public-synchronized-void-setpersistencecachesizebytes-long-cachesizeinbytes). Check this out for more on [cache size config](https://firebase.google.com/docs/firestore/manage-data/enable-offline#configure_cache_size)

Lastly, here's the [link to YouTube video(almost 30 min long but good introduction of firebase)](https://youtu.be/XrltP8bOHT0) explaining how firebase works including (Cloud firestore, Auth, Offline Persistance).

**Comment by holtzmak** [comment]
Great! Thank you for looking into this. I'm closing this issue because it appears to me we will be able to implement the logic we want in regards to unfinished ATRs and the database.
