### ISSUE TITLE
Create the Firebase Database interface implementation

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#130]
Related to #70 , and blocked by it. Also blocked by #129. Also blocked by #124.

- [x] Create the Firebase interface implementation that implements the generic queries in #70 to communicate with our Firebase instance

There should be unit (or integration) tests for this code using the object in #129. The tests may communicate with a mocked database at this time so we don't go over our Spark plan limit.

*If you are mocking the database instance, then the interface implementation should have a Firebase instance injected into it - meaning it takes it through the constructor!*

**Comment by SanaKhan1997** [comment]
When implementing atr queries, create two methods for retrieving bunch of documents:

 - [ ]  Method which only retrieves latest 10(use limit and order) atr documents
 - [ ]  Method which retrieves all documents
