### ISSUE TITLE
Structure Firebase Database Account Documents

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#151]
Structure the Firebase Database as per architecture documentation:
- [x] Structure Transporter Account data

You may find the guide to [Structuring your Firebase Database](https://firebase.google.com/docs/database/web/structure-data) to be useful. It also includes some tips on making our data scaleable.

**Comment by MummenRider** [comment]
Completed the structure for Transporter Account data in Firestore console
