### ISSUE TITLE
Create the Technical Requirements document

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#19]
Use a template similar to the Project Charter and Project Requirements.
Will be connected to these documents. See where the technical requirements are listed in the Project Requirements. 

The technical requirements are not implementation based. Think of requirements that developers would like on their project for development control:
- Automated build tool
- Automated testing
- Code Formatter
- Revision Control
- Unit testing, Integration testing, System testing

Or tools specific to development like:
- Cross-platform mobile development language
- Logging tools, alarm tools, email usage (maybe?)
- Databases (what kind of queries?)

**Important!**
1. Create tasks/issues for investigating tools/implementations for the technical requirements you identified
2. One such issue would be (for sure) the investigation of a database solution

**Comment by mansiPaTeLL** [comment]
@holtzmak Technical Requirements Document ready to be reviewed. #36 
The document is based on the investigation on certain tools and technologies and can be changed in future based on our needs.
