### ISSUE TITLE
Investigate getting GitHub badges onto our README

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#2]
Likely related to issue #1. Badges are provided by [Shields.io](https://github.com/badges) (investigate that link further)

**Comment by MummenRider** [comment]
**Are there privacy, licensing concerns that may prevent us from using the tool?**
Visit the link to generate the license: https://shields.io/category/license
**Is the tool free?**
Adding badges is free
**How difficult is it to use the tool?**
Adding badges to a github repository is really straightforward process.
**Does the tool provide useful "badges", reports, that present data such as code coverage and quality?**
Yes, badges will display information about the repository. Inormation such as code coverage percentage, Continuous Integration, Test/Code Coverage, etc.

**Comment by MummenRider** [comment]
Perhaps some additional information about badges.
**Why use badges on our repo?**
It increases the readability of the Readme.md and also gives a quick metrics about our repository. It will basically show the progress we made on our project (e.g. n of commits).

**Comment by holtzmak** [comment]
Thanks for looking into this! Needed to see if there were any gotchas. Looks like we'll add badges as we add GitHub actions that use the badge to report.
