### ISSUE TITLE
Investigate GUI development process

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#20]
We've sorta decided to use USM to being developing our GUI prototypes but this feels sort of ad hoc (to me, anyway). We should investigate if there exists a methodology to developing GUIs that isn't just the generation of prototypes as we see fit.

Create a wiki page to investigate GUI development processes. May also report that none were found if that is the case.

**Comment by MummenRider** [comment]
It seems like there is no concrete methodology for developing GUI. What I found out is that USM should not be use alone. One suggestion from a UX/UI designer with 10+ years experience in the field, UJM or User Journey Mapping should be done first (specially for new application) before USM. Furthermore, an article created by Adobe XD, suggested that User Flow should also be considered when developing GUI.
