### ISSUE TITLE
Add ability to change the transporter's image in the application

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#207]
This work goes in hand with the tasks #202 and

- [x] Use the ImagePicker/Screen in AccountEditingScreen to pick, save, and use the chosen image as the Transporter's image

This involves work with the `DatabaseService` to save/retrieve the image. Likely you need to change the database or JSON structure of `Transporter` too.

**Comment by MummenRider** [comment]
Note: I did not use Image Picker screen. I created the function inside the view model itself. This approach is based on this [YouTube](https://www.youtube.com/watch?v=KmyhznxYQ70&t=1394s) tutorial. The tutorial used bloc pattern, but the logic stayed the same for us. 

The roadmap for this task would be the following:
- [x] Add displayImageUrl field in Transporter
- [x] Add another query that will save images for Avatar user profile
- [x] Fetch the image using Image.network
