### ISSUE TITLE
Add the SettingsScreen and AboutScreen

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#208]
- [x] Add the SettingsScreen like the [GUI Prototype](https://xd.adobe.com/view/9a6f1910-d3ac-4fdf-b051-c2c78510ba32-cf3c/screen/58d55b67-910a-4061-b9ab-fefba271e0b8)
- [x] We don't need dark mode
- [x] We do need an `AboutScreen` that lists the license for the app, and the licenses of software we used in the app. 

Consider these discussions as your starting point to making the Licenses screen:
1. https://stackoverflow.com/questions/62685417/how-do-i-set-up-the-showlicensepage-function-to-work-with-flutter
2. https://www.reddit.com/r/FlutterDev/comments/echhz5/how_to_list_the_licenses_from_all_3rd_party/
3. https://api.flutter.dev/flutter/foundation/LicenseRegistry-class.html

**Comment by mansiPaTeLL** [comment]
I added SettingScreen and here how it looks. 

![image](https://user-images.githubusercontent.com/44125953/111950107-74e0e780-8aa7-11eb-9f51-8a37ede786a3.png)
