### ISSUE TITLE
Investigate User Story Mapping software

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#21]
Investigate USM software we can use. We've discussed that we'll want to use user stories to:
- Get a high-level idea of the transporter forms
- Use USM to build a sequence diagram of our expected "mega-form" such that our application can be used to fill different portions of the form at different times.
- Build GUI prototypes using the above-noted user stories

So, if we can have a visually-aided software (that isn't StoriesOnBoard, because we lose that "account" after the course is finished), we could better create user stories

**Comment by MummenRider** [comment]
### Here are the tools that are similar to StoriesOnBoard

**CardBoard** - As a CardBoarder you will be able to create unlimited public boards that are shared with the entire CardBoard community. While your boards will be accessible, only you can make changes. They advertise "Free for life" but also state that it is only free for 30 days.

**Miro** - Provides free access to their premium plan if you're a student. If you want to register as a student, you need some kind of proof like student id. For more information, go to: https://help.miro.com/hc/en-us/articles/360017730473-Education-Plan#:~:text=Miro%20provides%20a%20free%20Educational,Unlimited%20active%20boards
