### ISSUE TITLE
Test the administration POV of the application 

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#210]
- [x] Make an Admin account that we can reuse in demo, etc.
- [x] Test that when the admin is logged into the application, they can't use the `New` or `Active` buttons. An admin is not a Transporter.

**Comment by MummenRider** [comment]
In home screen, when new record is pressed, it works as expected. Modal pop-up that will show no permission to do so.
However, when 'active form', is pressed then pressed 'new form', the system  gets stuck on infinite loading. 

As I looked at the code, the setState was never put to idle when it catches the error. I will create a PR that should solve the problem
