### ISSUE TITLE
Update application GUI with a proper color theme

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#214]
- [x] Update the GUI and it's components to look better

**Comment by mansiPaTeLL** [comment]
@holtzmak @MummenRider Sana and I worked on GUI colour theme. Please review the designs below - 

**Color Scheme#1**
![Screen Shot 2021-03-11 at 5 01 30 PM](https://user-images.githubusercontent.com/44125953/110867299-1e480200-828c-11eb-9330-c73d324a2238.png)

**Color Scheme#2**
![Screen Shot 2021-03-11 at 5 02 25 PM](https://user-images.githubusercontent.com/44125953/110867332-21db8900-828c-11eb-812d-f190303d477a.png)

**Comment by holtzmak** [comment]
Gotta say no to design 2 because one of the other capstone projects has the exact same color scheme. However, I like that it's more white with color accents.

I think we should combine Design 1 and 2: I like the scheme of 1, but we should swap the brown and white (so, for example the Home page buttons are white on a brown background).

**Comment by mansiPaTeLL** [comment]
@holtzmak @MummenRider We have also selected some other schemes as well. We have already used scheme#1, and scheme#2. 
![unknown](https://user-images.githubusercontent.com/44125953/110867910-310f0680-828d-11eb-847f-6dfe823e2c35.png)

**Comment by mansiPaTeLL** [comment]
@SanaKhan1997 I am going to add color schemes into sign up, login and password reset.

**Comment by SanaKhan1997** [comment]
> @SanaKhan1997 I am going to add color schemes into sign up, login and password reset.

I've already applied color scheme to whole app. Will create PR soon
