### ISSUE TITLE
Investigate and create the ability to save images in Cloud Storage for Firebase

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#215]
- [x] Set up Cloud Storage and our database so we can save transporter acknowledgements with the ATR
- [x] Update DatabaseService accordingly

[From preliminary investigation](https://firebase.google.com/docs/storage) it looks like we upload the image to cloud storage and then use it's link in our cloud firestore.

This means we fetch and save records with the image URL/link, then read that link and contact cloud storage to fetch it to show in app. Similarly, we contact cloud storage first to save the image, then use the given link in cloud firestore.

**Comment by MummenRider** [comment]
I tried to install the latest firebase_storage and image picker but failed on doing so. It looks like the packages require us to be in flutter 2.0 in stable 2.0. I will try and install previous version
