### ISSUE TITLE
Create our User Story Mapping structure

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#22]
Create the USM structure:
1. Make different boards for different purposes: e.g. a board for breaking down and understanding how transporters use the forms, and a board for generic User Interaction/eXperience (UI/X) for the GUI (these are separate ideas!)
2. Creating a structure for how epics and user stories are to be written. e.g. I created a format for the Sprint Meeting Minutes entries in the Wiki

**Important!**
1. You will need to use the USM software investigated in #21 
2. You need to define how stories and epics (if we need epics) should be written.

**Comment by holtzmak** [comment]
@SanaKhan1997  and @MummenRider: I started investigating how we could use StoriesOnBoard for USM. I made the wiki page [User Story Mapping Guide](https://github.com/holtzmak/Humane-Transport/wiki/User-Story-Mapping-Guide) with instructions for how I think we could use the software to write the user stories. 

Some things that might not be great are that StoriesOnBoard has a finicky interface to work with, and I am not sure if the sequence of events comes through from the description I gave in the Wiki page. 

If you [go to our StoriesOnBoard board](https://landofooo.storiesonboard.com/m/humane-transport), I have some examples up for Transfer of Care cards.

**Comment by SanaKhan1997** [comment]
Thanks @holtzmak! By looking at StoriesOnBoard examples, I think it shows the sequence and description of story well. The only suggestion I have is may be we can add an alternate story of each step. For example, step("animal is injured during the offload" can have an alternate story("the animal requires contingency plan").

**Comment by holtzmak** [comment]
> Thanks @holtzmak! By looking at StoriesOnBoard examples, I think it shows the sequence and description of story well. The only suggestion I have is may be we can add an alternate story of each step. For example, step("animal is injured during the offload" can have an alternate story("the animal requires contingency plan").

The idea was to have the stories show the alternate branches for the step situation, so for step "animal is injured during the offload" there are stories "the animal isn't so injured as to require the contingency plan" and story "the animal requires contingency plan". There would be alternate steps unrelated to "animal is injured during the offload" like "animal has been discovered as perished during offload".
