### ISSUE TITLE
Create our GUI Prototyping structure

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#23]
Blocked by #22 and sort-of #20.
Create the structure (perhaps on a wiki page) to follow when creating GUI Prototypes, Lo-Fi, Mid-Fi, and Hi-Fi, based on the decisions made completing the above-noted tasks.

**Comment by mansiPaTeLL** [comment]
@holtzmak @MummenRider @SanaKhan1997 Please review [GUI-Prototyping-Structure](https://github.com/holtzmak/Humane-Transport/wiki/GUI-Prototyping-Structure)

**Comment by holtzmak** [comment]
- [x] Where did the descriptions of the three phases come from? Cite your source in Wiki for sure.

I'm happy with the described steps, it looks like 1 = our definition of LoFi, 2 = our definition of MidFi, and 3 = HiFi.

**Comment by mansiPaTeLL** [comment]
Included Resource Link.
