### ISSUE TITLE
Create the user testing plan and results report

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#238]
This is a custom report outlining how we designed user tests (the feedback form), how we implemented them (Google form), and their ultimate results (that responses favored Design 2/B)

- [x] Start with a section describing how we designed the user feedback documents (why do we collection information like age? what sorts of questions did we ask, were they qualitative/quantitative? etc.)
- [x] Write about why we used a Google form, why this over alternatives (like deploying a beta version of the app? or in-person testing? _Hint: transporter's don't have time to sit down and do this with us right now_)
- [x] Write about the results of the feedback we received (we revised the prototypes according to what feedback? what was most favored?)

Put the report in `documentation/closing` folder when complete.

**Comment by holtzmak** [comment]
Might wanna take a look at the information from the past prototype tasks, Clark or Mansi may have some information in the task comments or even in the wiki pages.

**Comment by MummenRider** [comment]
@holtzmak With help of Mansi, I think I completed this task.[ Click me](https://docs.google.com/document/d/1puq7Qo_M8hbiiD_W16pZQ7t2AkFoYk5-aMorkvdeCZk/edit) to go to document. You're also welcome to make changes/add something there
