### ISSUE TITLE
Create the code quality review report

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#239]
Write a 5-page maximum report on the quality of the code we've written, our testing process, and other tools and things we did to ensure good quality code. 

- [x] Use the [code review checklist](https://www.evoketechnologies.com/blog/code-review-checklist-perform-effective-code-reviews/) and answer it's questions as part of the report (alongside screenshots of our own code/tools like GitHub actions)
> Each section of the checklist should correspond to 1 page or so

**Comment by MummenRider** [comment]
@holtzmak I think I completed this. You're welcome to check the information I added. [Click me](https://docs.google.com/document/d/1S4zhORYksJKMl87x6rISMMSNcBzRbLVlHTWs-Z2cgRM/edit) to go to document
