### ISSUE TITLE
Investigate options for application database

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#25]
Investigate and compare some options for our application database:
1. Contact the university and ask if we could use a university-owned machines as our server, and what database options exist
2. Compare using a private server (our own machine) with database service (e.g. MongoDB) and AWS virtual machine with a database service
3. We may need a mobile "database" in case we can't communicate with server, what are our options for that (text files?)

Create a Wiki page with the options.

**Comment by mansiPaTeLL** [comment]
I've contacted prof. Craig Gelowitz. He has provided a AWS EC2 Instance. 

What is EC2? 
An EC2 instance is a virtual server in Amazon's Elastic Compute Cloud (EC2) for running applications on the Amazon Web Services (AWS) infrastructure. AWS is a comprehensive, evolving cloud computing platform; EC2 is a service that allows us to run application programs in the computing environment. We can run our Database Server on the AWS EC2 instance. We can install any database server we would like to do. 

I will show you guys how you all can access the server. 

There are few options, I've found for our database server for a mobile application. They are - 

1. SQLite: Embedded database, common usage is to provide local data storage capabilities on mobile phones
2. MongoDB: A schema-less, JSON document database which is known for its flexibility and scalability
3. MariaDB: A popular open source relational database
