### ISSUE TITLE
Create the Project Poster(s) 

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#251]
Create the conference poster as required for the course. This is a semi-technical poster so it should have some description text on it.

We also require an advertisement poster for social media sharing purposes.

Some feedback from the course instructor:
1. simplify images
2. remove MVVM images
3. add signifiers like green/red checkmarks
4. images need to fit the space and be legible on the screen at 100% zoom, no squishing images 
5. we should tell the story in the poster, less technical and more conference-y
6. no scrum agile and no project docs or images

**Comment by mansiPaTeLL** [comment]
![Slide 4](https://user-images.githubusercontent.com/32527219/113915077-8e6a7a80-979b-11eb-9969-74e85a6634ba.png)

@holtzmak @MummenRider @SanaKhan1997 Review Slide#4 - 
https://docs.google.com/presentation/d/1QLr6kWxI1kuKb7aBMde1dKfLGxpPS7FZ5gV16YqBe44/edit#slide=id.gce6aea4c29_0_0

**Comment by mansiPaTeLL** [comment]
@holtzmak @MummenRider @SanaKhan1997 Please review the Advertisement poster with new images. 

![Humane-Transport-Advertisment-Poster](https://user-images.githubusercontent.com/44125953/113925757-a0064f00-97a8-11eb-8187-e0c622547f63.png)

**Comment by holtzmak** [comment]
@mansiPaTeLL Both posters look good to me. We've updated the home screen and form already.... I'll send you the new screen shots for the advertisement poster!
