### ISSUE TITLE
Create the Project Commercial

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#252]
Create the project commercial as required by the course. This commercial should be short, 1 - 3 minutes. There are no other requirements and we're free to be as creative as we want.

Some feedback from the course instructor:
1. the commercial should be relatable
2. try an improv skit

**Comment by SanaKhan1997** [comment]
[Commercial Script](https://docs.google.com/document/d/1M7u1GEHmZxhxF-8egwBxWBlCcmANdQujv7JQPKAtHK8/edit?usp=sharing)

**Comment by SanaKhan1997** [comment]
[Link to Final Commercial](https://youtu.be/r14XWNl9UI8)
