### ISSUE TITLE
Investigate Client-Server (Architecture) documentation

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#27]
Investigate ways we could document our expected Client-Server architecture/design:
1. We could start drawing Client-Server Architecture UML Diagrams (goes in hand with #26 )
2. What about other/more ways to document server building besides writing code and architecture drawings?

Create a Wiki page with your findings (and maybe start the UML Diagrams depending on #26 )

**Comment by mansiPaTeLL** [comment]
@holtzmak Review Wiki- [Client-Server Architecture Tools](https://github.com/holtzmak/Humane-Transport/wiki/Client-Server-Architecture-Design-Tools:-SmartDraw-&-Draw.io).

**Comment by mansiPaTeLL** [comment]
I've investigated into these tools to create software diagrams. Using this tools we can start drawing the UML diagrams/User story diagrams based on Project Requirements. After creating client-server model diagrams, we can create word documents to explain the diagrams and include these diagrams into it to create complete documentation.

**Comment by holtzmak** [comment]
@mansiPaTeLL comparison looks good. I've used draw.io frequently in the past, there's only one problem I see with it: you have to be perfect when moving and selecting objects or it will look slightly off (there's no "snap" feature).

A question for you: what about Lucidchart? Sana and yourself have been using it.

Some food for thought:

RE: Client-Server architecture design, is the only way to design these things is to use UML, entity drawings and a written explanation? I suppose we could design these iteratively to achieve a better result. 

What about known design patterns for client-server architecture? I've seen design patterns like MVVC for example. When we go to start making the client-server architecture, we should make a running document of designs.

**Comment by holtzmak** [comment]
Making a note here from a previous conversation:

We treat Client Architecture, Server Architecture, and Database Architecture differently. Each are project-defined as:
1. Client Architecture - The architecture (classes) which define our client code, such as code that will build the GUI but not exactly the code that organizes how data is shown to the user (this was task #20) _(We'll likely have a meeting soon to further define how client code is separate from GUI-describing code)_
2. Server Architecture - The classes which define our business logic (such as the handling of form objects and communication with the database)
3. Database Architecture - The table definition in the database that will store our form objects

This task is meant for investigating both Client and Server architecture, @mansiPaTeLL you've found some tools that will allow us to make the documentation but have not yet investigated how to design Client and Server architecture - meaning we should look into the process, i.e. a process could be:
1. Create GUI prototype that our client wants
1. Determine the different form element classes that can be taken from the GUI: could a UML diagram help us model this somehow?
1. Determine how the form classes should be taken from the Client into the Server (i.e. MVC pattern, and then how do we know the best pattern? Do we consider procs/cons to using MVC?)

A decent example about how to make Client-Server architecture (one way, by incrementing documentation) is the Client-Server Architecture described [here](http://www.cs.sjsu.edu/~pearce/oom/ood/distArch/server). I would say this is somewhat ad-hoc as it uses best practices but doesn't really critically evaluate or define the final chosen pattern (just defines how they got to the pattern).

**Comment by mansiPaTeLL** [comment]
@holtzmak Thank you. This makes more sense to me now. I will start documenting the process and making comparison document of different patterns.

**Comment by mansiPaTeLL** [comment]
So, The C4 model procedure is very helpful to start our client-server architecture model. Using this procedure, we can start documenting big picture (Context Diagram) to design our application system. Please see the wiki [C4-Model-for-Client-Server-Architecture](https://github.com/holtzmak/Humane-Transport/wiki/C4-Model-for-Client-Server-Architecture) on C4 model or visit [C4 Model site](https://c4model.com/)

**Comment by mansiPaTeLL** [comment]
@holtzmak Ready to Review.

**Comment by holtzmak** [comment]
The C4 Model is very good, and I think will be perfect for our uses. Thank you for writing up the two wiki pages.

Let's make a task for generating the first draft of the client-server architecture. This will be of the best opinion of the people working on the task, keeping in mind good architecture practices and the work we expect the app to do: interact with the user, do work on the forms, interact with the database, log actions the application took for future debugging, etc.
