### ISSUE TITLE
Breakdown Transfer of Care Documentation

### ISSUE THREAD

**Issue by SanaKhan1997** [holtzmak/Humane-Transport#30]
EDIT: Issue split from #24, see #24 for further information
This issue will only focus on Transfer of care documentation
- Form requirements
- rules & regulations
- formats
- template

**Comment by SanaKhan1997** [comment]
Review required @holtzmak 
[Wiki Page](https://github.com/holtzmak/Humane-Transport/wiki/Transfer-of-Care-Document-Breakdown)

**Comment by holtzmak** [comment]
Looks good! Few things I noticed:
1. Very nice that you quoted HAR Pt. XII sections directly... should we do this for every breakdown or would that be excessive?
2. What is a "...provision of legal receipt will be considered as acknowledgement."? 
- [x] We should look into what a legal receipt is and add additional comment on the Wiki page with its definition (relative to the HAR)

**Comment by SanaKhan1997** [comment]
I think we should provide HAR sections specific for each document. This would allow people to refer back to the original rules & regulations specified by HAR for that particular document.
Yes I will look more into legal receipt but from what's mentioned on the interpretive guidance it is a receipt that is retrievable by receiver(so they can refer back and confirms that this receipt was issued by them) and unalterable(so probably a printed or digital copy which can't be changed once the delivery is confirmed).

**Comment by SanaKhan1997** [comment]
@holtzmak here's the explanation of legal receipt that I found at  HAR guidance:
**"they are to acknowledge receipt of the load with written documentation that is retrievable and unalterable for legal purposes"**
I have updated this information on the wiki page as well.
