### ISSUE TITLE
Feed, Water & Rest Record Breakdown

### ISSUE THREAD

**Issue by SanaKhan1997** [holtzmak/Humane-Transport#31]
EDIT: Issue split from #24, see #24 for further information
This issue will focus on all rules & regulations, requirements and format of FWR document.

**Comment by SanaKhan1997** [comment]
@holtzmak Here's the [wiki page for FWR](https://github.com/holtzmak/Humane-Transport/wiki/Feed,-Water-&-Rest-Document-Breakdown)

**Comment by holtzmak** [comment]
This looks good. I think it overlaps a bit with the other mentioned forms a fair bit, so additional information can then be found in other breakdowns if needed.
