### ISSUE TITLE
Investigate one more multiplatform project template

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#33]
After investigating Kotlin's Multiplatform Mobile (KMM) project template in #26, it would be in our best interest to try out at least one more way of creating a multiplatform project to see if it's easier to use.

(Copied from #26, try out something similar to the following):

Investigate how to write/get working the cross-platform (agnostic) GUI code:
1. Start investigating another, well-known multiplatform project/language
2. Could start a Wiki page with the options cross-platform code could be written
3. Get a window running on android and iOS (this is expected to be a dummy window, if you write the "real-thing" we could also merge into our codebase!)

**Comment by MummenRider** [comment]
My experience : Setting up flutter in macOS is fairly easy. I haven't tried this on windows yet.
Future Goal: Explore Flutter documentation and maybe see Dart Language

**Comment by holtzmak** [comment]
> My experience : Setting up flutter in macOS is fairly easy. I haven't tried this on windows yet.
> Future Goal: Explore Flutter documentation and maybe see Dart Language

Does it feel like Flutter is strong competition for KMM with its better integration with Android Studio? If we all end up using the same IDE (especially one that can run iOS without XCode* specifically) we could probably put configuration files under revision control so people don't have to figure out on their own (do it once kinda thing).

*I'm pretty sure you still had to download XCode tools, but that's minimal compared to the 40GB XCode can inflate to

**Comment by mansiPaTeLL** [comment]
@MummenRider Great. Thanks to look into this. I will also help you out here with the investigations.

**Comment by MummenRider** [comment]
If you want to use ios simulator, then downloading xcode is required. Flutter is indeed a huge competitor to KMM and we should really consider using flutter instead. As for IDE, we don't need huge IDE such as intellij, android studio or xcode, we can use a lightweight ide like VScode. I am closing this as I believe that I investigated enough to resolve this issue.
