### ISSUE TITLE
Create Sequence Diagram for mega-form structure

### ISSUE THREAD

**Issue by SanaKhan1997** [holtzmak/Humane-Transport#37]
Show a sequence of form elements to be filled during the transportation following a sequence of timeline.

**Comment by SanaKhan1997** [comment]
[Mega-form Sequence Diagram](https://github.com/holtzmak/Humane-Transport/blob/SanaKhan1997-patch-1/documentation/Megaform%20Sequence%20Diagram.svg)

**Comment by holtzmak** [comment]
TBH I was expecting just a timeline of events, the UML Sequence Diagram you've made also details some behaviour with the database which is really useful for #40 and related. Thanks!
