### ISSUE TITLE
Create the Animal Transport Record USM stories

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#41]
Brainstorm and write the Animal Transport Record stories from the transporter's action-based perspective (not the application-interaction perspective). You'll put the stories on their respective board as decided in #22 and by #39.

These stories are determined in part by the mega-form, created in #38 and the sequence diagram for transporter activities in #37. When writing a story that overlaps with interaction with another form type, i.e.:

"The transporter notices an animal is injured during FWR. The animal is fed and watered because it appears to able to without being bothered by it's injury. While the animal is resting, the contingency plan says to..." _(This story is not the structure that would be determined in #22! Follow the structure in #22 )_

You'll have to discuss with the assignee of the other form type stories to be sure that only one person is doing the story. Typically, we'll have the first form type mentioned in the story be the owner of that story (in the example above, the assignee doing FWR stories will write the story instead of the contingency plan stories assignee.

**Comment by SanaKhan1997** [comment]
@holtzmak here's the first draft [ATR stories](https://docs.google.com/document/d/1C_0mWPUDY90eK_3kN2LisLEhM0Ia4WtmCGWrhyU1kl8/edit?usp=sharing)

**Comment by holtzmak** [comment]
A good first draft. Added comments to the document, probably nothing to change at this point - I think we consolidate when we're ready to move the stories to StoriesOnBoard (because we can click and drag around and whatnot)
