### ISSUE TITLE
Create the Contingency Plan USM Stories

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#43]
Brainstorm and write the Contingency plan stories from the transporter's action-based perspective (not the application-interaction perspective). You'll put the stories on their respective board as decided in #22 and by #39.

These stories are determined in part by the mega-form, created in #38 and the sequence diagram for transporter activities in #37. When writing a story that overlaps with interaction with another form type, i.e.:

"The transporter notices an animal is injured during FWR. The animal is fed and watered because it appears to able to without being bothered by it's injury. While the animal is resting, the contingency plan says to..." _(This story is not the structure that would be determined in #22! Follow the structure in #22 )_

You'll have to discuss with the assignee of the other form type stories to be sure that only one person is doing the story. Typically, we'll have the first form type mentioned in the story be the owner of that story (in the example above, the assignee doing FWR stories will write the story instead of the contingency plan stories assignee.

**Comment by holtzmak** [comment]
@SanaKhan1997 , @MummenRider Please find the Contingency plan user stories for review [here](https://docs.google.com/document/d/1rNKnG4ojWrwrDZ4cgZQ45COZNYcSbBSoK77l4kYc2GA/edit?usp=sharing). (Note that I am aware of the possible overlap of some stories, I believe consolidation and reducing of stories is best done on StoriesOnBoard because it will be better to visual changes there)

**Comment by SanaKhan1997** [comment]
> @SanaKhan1997 , @MummenRider Please find the Contingency plan user stories for review [here](https://docs.google.com/document/d/1rNKnG4ojWrwrDZ4cgZQ45COZNYcSbBSoK77l4kYc2GA/edit?usp=sharing). (Note that I am aware of the possible overlap of some stories, I believe consolidation and reducing of stories is best done on StoriesOnBoard because it will be better to visual changes there)

Great job! It covers everything.
