### ISSUE TITLE
Create the Transfer of Care USM Stories

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#44]
Brainstorm and write the Transfer of Care stories from the transporter's action-based perspective (not the application-interaction perspective). You'll put the stories on their respective board as decided in #22 and by #39.

These stories are determined in part by the mega-form, created in #38 and the sequence diagram for transporter activities in #37. When writing a story that overlaps with interaction with another form type, i.e.:

"The transporter notices an animal is injured during FWR. The animal is fed and watered because it appears to able to without being bothered by it's injury. While the animal is resting, the contingency plan says to..." _(This story is not the structure that would be determined in #22! Follow the structure in #22 )_

You'll have to discuss with the assignee of the other form type stories to be sure that only one person is doing the story. Typically, we'll have the first form type mentioned in the story be the owner of that story (in the example above, the assignee doing FWR stories will write the story instead of the contingency plan stories assignee.

**Comment by holtzmak** [comment]
@SanaKhan1997 Please find a first draft of the user stories [here](https://docs.google.com/document/d/1_choggW326L2j8otjVHxzqGRIDdvYZ9I7e8_aLubmEU/edit?usp=sharing) for review.

**Comment by SanaKhan1997** [comment]
> @SanaKhan1997 Please find a first draft of the user stories [here](https://docs.google.com/document/d/1_choggW326L2j8otjVHxzqGRIDdvYZ9I7e8_aLubmEU/edit?usp=sharing) for review.

Draft seems pretty accurate and covers almost everything.
