### ISSUE TITLE
Create the CFIA Inspector-related (and other) USM Stories

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#45]
Brainstorm and write the stories where a CFIA inspector wants to see the transporter's records from the transporter's action-based perspective (not the application-interaction perspective).  Consider also other situations that are not exactly covered by our Animal Transport Record Forms.

You'll put the stories on their respective board as decided in #22 and by #39.

These stories are determined in part by the mega-form, created in #38 and the sequence diagram for transporter activities in #37. When writing a story that overlaps with interaction with another form type, i.e.:

"The transporter notices an animal is injured during FWR. The animal is fed and watered because it appears to able to without being bothered by it's injury. While the animal is resting, the contingency plan says to..." _(This story is not the structure that would be determined in #22! Follow the structure in #22 )_

You'll have to discuss with the assignee of the other form type stories to be sure that only one person is doing the story. Typically, we'll have the first form type mentioned in the story be the owner of that story (in the example above, the assignee doing FWR stories will write the story instead of the contingency plan stories assignee.

**Comment by mansiPaTeLL** [comment]
@holtzmak @SanaKhan1997 Ready to Review - [CFIA Inspector-related Stories](https://docs.google.com/document/d/1-dezlNxXrzodzd1Ob3WaqEZTWr_TDg7Txj2S8nqmHdM/edit?usp=sharing)

**Comment by holtzmak** [comment]
Had a peek, a good first draft and will need to change the focus from what CFIA inspectors do to what transporters need to do in response to CFIA orders or inspector questions. I think some of your questions in the document will be answered in our next client meeting.

**Comment by mansiPaTeLL** [comment]
@holtzmak @SanaKhan1997 Ready to Review Second Draft - [CFIA Inspector-related Stories](https://docs.google.com/document/d/1-dezlNxXrzodzd1Ob3WaqEZTWr_TDg7Txj2S8nqmHdM/edit). Please review page 3-5 in this document.

**Comment by SanaKhan1997** [comment]
> @holtzmak @SanaKhan1997 Ready to Review Second Draft - [CFIA Inspector-related Stories](https://docs.google.com/document/d/1-dezlNxXrzodzd1Ob3WaqEZTWr_TDg7Txj2S8nqmHdM/edit). Please review page 3-5 in this document.
Thanks! they are looking good to me.

**Comment by holtzmak** [comment]
Second draft is great. It's really good to flag that the transporter would at times be expected to provide proof of training.

Please throw the stories up on our [StoriesOnBoard](https://landofooo.storiesonboard.com/m/humane-transport).

**Comment by mansiPaTeLL** [comment]
Added on our [StoriesOnBoard](https://landofooo.storiesonboard.com/m/humane-transport).
