### ISSUE TITLE
Create our User Journey Mapping structure

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#47]
Like #22, create the User Journey Mapping (UJM) structure:
1. How should we generate UJMs? A drawing, maybe? e.g. [like this](https://d2slcw3kip6qmk.cloudfront.net/marketing/blog/updates/customer-journey-map-example.png) (Do we need to go as far as personas?)
2. Discover important landing pages for our app (ignoring how the information may be displayed on such a page) i.e. Login page, history page, form pages.

Several UJM issues rely on this task, so expect there to be revisions needed when people start generating those.

**Comment by MummenRider** [comment]
1.) According to Nielsen Norman Group, here are the following key components when creating a UJM

- Actor
- Scenario + Expectations
- Journey Phases
- Actions, Mindsets, and Emotions
- Opportunities
**Note: ** For more info, go to https://www.nngroup.com/articles/journey-mapping-101/
Generating UJM - [Figma](https://www.figma.com/community/file/812358656900783385) can be used to create UJM. 

I will investigate important landing pages soon

**Comment by SanaKhan1997** [comment]
> 1.) According to Nielsen Norman Group, here are the following key components when creating a UJM
> 
> * Actor
> * Scenario + Expectations
> * Journey Phases
> * Actions, Mindsets, and Emotions
> * Opportunities
>   **Note: ** For more info, go to https://www.nngroup.com/articles/journey-mapping-101/
>   Generating UJM - [Figma](https://www.figma.com/community/file/812358656900783385) can be used to create UJM.
> 
> I will investigate important landing pages soon

I created a document containing a brief description of possible landing pages [here](https://docs.google.com/document/d/1elmwDl1mahdoGgM2dJ_MGhT75FXoGTlytCAQLIIoPyQ/edit?usp=sharing). Feel free to add more.

**Comment by holtzmak** [comment]
This is a good first cut. I think this task can be considered done if we write up how we should make UJMs (like, our specific procedure, I don't see us having phases quite like the nngroup suggests).

I think the landing pages brainstormed are also good for our base application, and keeping note separate the extra pages that could be useful (like the GPS page suggested, but I think google does a better job than something we could do).

**Comment by holtzmak** [comment]
As per Scrum discussion Nov 13, 2020: UJMs will be brainstormed up using the combination of our USMs from StoriesOnBoard and developed using the [NN/g template for UJMs](https://media.nngroup.com/media/articles/attachments/JMTemplate.pdf). The instructions on the website, linked above, are sufficient.
