### ISSUE TITLE
Create our GUI Prototype Testing structure

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#53]
Create a format for recording the results of our GUI Prototype tests. We'll want to quantify and qualify the opinions of our testers:
1. You could make a table with columns for things like: initial opinion (qualify), how many testers liked the prototype best (quantify), frustrations (qualify, describe what was really bad), etc.
2. Investigate online if perhaps alpha-beta testing is useful
3. Culminate your thoughts into a testing document that can be filled out during testing

This kind of template likely needs to go into the `documentation` folder of our codebase.

**Comment by mansiPaTeLL** [comment]
Review Shared Folder - [Usability Testing Documents](https://drive.google.com/drive/folders/1A_11gJoTYauCspRdNuFMFZYHnB19-t--?usp=sharing)
@holtzmak @MummenRider @SanaKhan1997

**Comment by holtzmak** [comment]
@mansiPaTeLL Wow, the Google Form is a great idea if we can't make a time to meet transporters - we can give this to our client to hand out and we'll gather results. I think still worth our time to host ftf meetings where we can (and for the first few while we tweak things for better results).

I've never personally been a fan of feature testing like this: "Can you save a file? Can you this/that/that over there?" and asking difficulty. I wonder if Tim has any comments on making things more engaging and less technical.

**Comment by holtzmak** [comment]
@mansiPaTeLL can you describe which document you intend to use and how?

**Comment by mansiPaTeLL** [comment]
@holtzmak  So, if we can't meet with the transporter, we can definitely send a video, explaining what they will do and the User Testing Form. So that they can do the testing in their own time and enter the feedback in the form. We are definitely using the Google Form because I think it will be easy to record the feedback.

**Comment by holtzmak** [comment]
@mansiPaTeLL That's a good idea, we might have to do that.
