### ISSUE TITLE
Create our Lo-Fi and Mid-Fi GUI Prototypes from UJMs

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#54]
Generate some GUI prototypes from our UJM tasks using the structure outlined in #23. 
1. Start with Lo-Fi
2. And then make Mid-Fi (not as super nice as Hi-Fi, but clearer than the sketches for Lo-Fi)
3. Show the Client and get feedback on the Mid-Fi prototypes
4. Record the feedback according to #53.

We'll probably save drawings and such in the `documentation` folder of our codebase. Consider making subfolders to organize documentation as things might be getting a bit cramped in there.

**Comment by mansiPaTeLL** [comment]
@holtzmak @MummenRider @SanaKhan1997 Please review the Mid-Fi Design#1. [Please click here to review](https://xd.adobe.com/view/9c2642bc-9484-44ed-a6e1-3fa065fcfcbd-c975/)

**Comment by mansiPaTeLL** [comment]
@holtzmak @MummenRider @SanaKhan1997 Please review the Mid-Fi Design#2. [Please click here to review](https://xd.adobe.com/view/9a6f1910-d3ac-4fdf-b051-c2c78510ba32-cf3c/)

**Comment by mansiPaTeLL** [comment]
I have added GUI prototype folder. So far, we have completed Lo-fi and Mid-fi prototypes. Once, we receive the feedback from our client, We will create an issue to gather and record all the feedback. According to feedbacks, we will move to Hi-Fi prototypes.
