### ISSUE TITLE
Site Revision

### ISSUE THREAD

**Issue by SanaKhan1997** [holtzmak/Humane-Transport#59]
- [x] Create new links for progress(USM, UJM)

- [x] Brief explanation for current documentation

Team members are free to suggest changes and improvements for site.

**Comment by holtzmak** [comment]
We should review what information is useful on the site, and if we have added every deliverable, important progress point, etc. Maybe add disclaimers for software-heavy documents.

I would personally like to see an update to the UI colours - the site itself is discoverable and the layout is fine, but the colors should be improved to be less blocky. For example, [Team BEEJ](https://ayonoaduo.github.io/BEEJ-Project/) has a very clean, modern theme for their site and while the theme may be some standard one they've borrowed from the internet, it still is relative to their project idea (the leaves <=> reporting about the environment).

We could look into farm-related themes, or use photographs from Canadian photographers (with permission) to enhance the importance of the area we're working in: animal welfare.

**Comment by SanaKhan1997** [comment]
- [x] Select documents and other content for website

- [x] Use relevant images([unsplash](https://unsplash.com/s/photos/animal-welfare) allows use of images for projects)

- [x] Select template and color scheme for site(there are some really cool color scheme generators available online)

**Comment by SanaKhan1997** [comment]
These are health and farm related color schemes. Background will be white mostly and color will be applied only on links, header, footer and navigation bars.
![Untitled collage](https://user-images.githubusercontent.com/61838681/99743867-2e00c800-2a9c-11eb-98c1-f13d20b7fdba.png)

**Comment by SanaKhan1997** [comment]
Template 3
<img width="234" alt="T1(a)" src="https://user-images.githubusercontent.com/61838681/99886733-72a77300-2c04-11eb-8bcf-02b8245cc1fb.PNG">
<img width="228" alt="T1(b)" src="https://user-images.githubusercontent.com/61838681/99886738-7a671780-2c04-11eb-8ccb-8a55d7bc9056.PNG">

**Comment by holtzmak** [comment]
This is so much more professional! Really digging the layout. Could use a little more colour for highlighting, for example the boxes surrounding the team names could use a could grade (meaning, not bright but some tint to the box to stand out a little more).

BTW my last name isn't Holtzmak (couldn't nab the `holtzman` GitHub name, and my uni email is holtzmak, too, because UofR naming system is silly)

**Comment by SanaKhan1997** [comment]
Template 5
<img width="227" alt="T2a" src="https://user-images.githubusercontent.com/61838681/99887973-70e2ad00-2c0e-11eb-8b1b-6e97bb034717.PNG">
<img width="222" alt="T2b" src="https://user-images.githubusercontent.com/61838681/99887977-793ae800-2c0e-11eb-8244-acb51cffd9b6.PNG">
Header looks like this:
<img width="865" alt="header" src="https://user-images.githubusercontent.com/61838681/99888049-17c74900-2c0f-11eb-84ac-f74b63595d8f.PNG">

**Comment by holtzmak** [comment]
> Template 5

This is so, so, so, so, so good! I love this template the most!

**Comment by SanaKhan1997** [comment]
Template 4
<img width="226" alt="T3a" src="https://user-images.githubusercontent.com/61838681/99917367-60e1d080-2cd5-11eb-9293-d5453d6ea0bc.PNG">
<img width="225" alt="T3b" src="https://user-images.githubusercontent.com/61838681/99917370-66d7b180-2cd5-11eb-8d5e-f5965933cc1d.PNG">

**Comment by SanaKhan1997** [comment]
You guys are free to pick features between templates and select the templates provided above

**Comment by MummenRider** [comment]
I love template #5

**Comment by mansiPaTeLL** [comment]
I also like the template 5. Really looking good. Thanks @SanaKhan1997

**Comment by SanaKhan1997** [comment]
Website has been updated! Review one more time and let me know if it needs to change a thing.

**Comment by holtzmak** [comment]
I can think of little fun things that would be useful, but not required:
- [x] What if the team member names were links to our GitHubs?
- [x] I need to update the Sprint chart again...

Otherwise, very good and concise!

**Comment by holtzmak** [comment]
@SanaKhan1997 updated Sprint Gantt chart now, but it can wait to be uploaded with all the changes we have occurring at once this Sprint.

**Comment by holtzmak** [comment]
Omg, sorry but I also noticed you've written yourself as the "Scrum Owner" on the site as well! Haha, I think we're all becoming blind to the word scrum now.
![Screen Shot 2020-11-23 at 3 44 25 PM](https://user-images.githubusercontent.com/32527219/100018946-e2ebfb00-2da2-11eb-96bc-8297eecb5fd9.png)

**Comment by holtzmak** [comment]
One more suggestion because I'm just like that: what if we shared the group email on the site for queries?

**Comment by SanaKhan1997** [comment]
> One more suggestion because I'm just like that: what if we shared the group email on the site for queries?

Scrum Owner changed to Scrum Product Owner and added email as well.
