### ISSUE TITLE
Start Project Charter

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#6]
Fill out out sections that we have information, now, on.
1. Create documentation folder in code and put Project Charter PDF in it (submit for PR review)
2. Create additional tasks for sections that need more information i.e.: Project Specification

**Comment by SanaKhan1997** [comment]
For Reviews:
[Project Charter.pdf](https://github.com/holtzmak/Humane-Transport/files/5251110/Project.Charter.pdf)
