### ISSUE TITLE
Create our first draft of the Database Architecture Design

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#69]
Create our first draft of our database architecture design as per the [data modelling design process](https://github.com/holtzmak/Humane-Transport/wiki/Data-Modelling-Design-Process). 

_We say first draft here as we'll expect to expand on the design, or expect the design to expand, in the future with the addition of other systems the application will communicate with (like more than one database)._

Mansi has started the design process in #40 , see her comments in the issue. Consider the security provisions in #68 , either in this task or another task if we separate the login information from the animal transport record information (which we should).

Brainstorm the responsibilities of the database and how other people may want to access information in the database. For example, the FWR information can probably just be grouped with the ATR information, but perhaps the ToC information should be a separate record if other people than the transporter would want to have or access the information (because they don't care about FWR, etc.).

This task is done when (depending on how the work feels, each of these could be split to it's own task):
- [x] The first draft of the data model(s) for the animal transport record is done
- [x] The first draft of the data model(s) for transporter login is done

Final note: First draft is an important word in this task, when working with SQLite, etc. we'll probably find that the entities we thought we'd use are totally different (but the responsibilities stay the same). Thus, when we have made progress with the database, we can go back and create another draft of the data model with a better idea of it.

I do foresee that going back into the architecture drawings could slow down development, hence why I've mentioned before that if we have the general idea, we can forge forward without redrawing design (the code is now our design); We'll revisit the design drawings when we have the time.

**Comment by holtzmak** [comment]
Additionally, should discuss with the assignee of #70 about how similar or different the local database should be to the remote. Obviously, the local database on the phone isn't a real database at all - so, it should probably have a different format to the remote database/or it should have a format similar to the interface of the remote database but not based on query format or similar. 

This task is not about designing the local database, as it is somewhat different to a real database and different to the interface to either database (you may wish to view the client-server architecture drawings to understand this).

**Comment by mansiPaTeLL** [comment]
Tasks :

- [x] Cleaning up the entity/attribute list
- [x] ATR Data Model 
- [x] Transporter Login Data Model

**Comment by mansiPaTeLL** [comment]
@holtzmak @SanaKhan1997  I have a question here regarding the ToC record. If anyone wants to access ToC Record, what exact information should be retrievable from the database? 
(From HAR Regulations)The ToC written document includes:
    the conditions of the animal(s) on arrival
    the date, time, and place where the animal(s) were last fed/watered/rested
    the date, time and place of arrival;
    an acknowledgement from the consignee that the animal(s) has been received and is/are now in their care (and any inconsistencies they note from the driver's documents)

For example, Let's assume Transporter submits the ATR form. Now, the ToC record is requested by someone, should we fetch data of Transporter's Information, Loading Vehicle Information, Delivery Information and Acknowledgments or all the information should be fetched from ATR?

**Comment by holtzmak** [comment]
@mansiPaTeLL Sana created [the consolidated ATR](https://github.com/holtzmak/Humane-Transport/blob/master/documentation/specifications/Consolidated%20Animal%20Transport%20Form.pdf), those sections outlined in green are those which are ToC and must be retrieved with the ToC record.

Therefore, I believe that we do indeed fetch the Transporter's information, etc. when requesting ToC - the requester may not need all of it, but all of it is required to call it ToC record, so we group it all together.

**Comment by mansiPaTeLL** [comment]
@holtzmak @MummenRider Please review. Thank you. - [Data Models](https://drive.google.com/drive/folders/1gPd3G4MeIgh0tuK381sGyNK8R9iX2MLk?usp=sharing)

**Comment by holtzmak** [comment]
@mansiPaTeLL Reviewing now, do I need to review the "Second copy of initial entity diagrams"?

**Comment by holtzmak** [comment]
1. Not sure about entities like ShipperInfo, TransporterInfo, VehicleInfo being able to live in the database with no connecting entities. I don't think anything in the system can live without other entities besides transporter accounts.

What I mean is, you've used the [crow's foot notation](http://www2.cs.uregina.ca/~bernatja/crowsfoot.html) to describe that the above ****Infos are 0 to many. 
- [x] I think it should be 1 or more.

2. Good idea to consider not having duplicates of the same record - maybe we can consider autocomplete records as a future MVP (alongside audio, video) (those are starting to look ambitious at this time, we've lots to do).

3. I wonder, with so many string fields, if we can't define a custom field for our entities - this would prevent accidental injection of malicious code because it wouldn't pass formatting checks. Also, it would warn people if they accidentally mixed up something like AdditionalInformationOfCompromisedAnimal and InfoOfSpecialNeeds.
- [x] Can/should we define custom field formats?

4. How would we generate something like AnimalGroup_Id? If the same group of animals is transported by a different transporter, I don't see how the system would assign that group the same ID as last movement.
- [x] How could we assign the same AnimalGroup_Id across transporters moving the same group of animals?

5. Not sure how I feel about the Company entity. I see why you've split it off, but not all entities related to the Company entity need all of its fields. I think giving access to other fields is asking for trouble in the future if we mistaken give access to all the fields in an entity in a database fetch. Not sure how I'd resolve this, though....

**Comment by mansiPaTeLL** [comment]
> 
> 
> @mansiPaTeLL Reviewing now, do I need to review the "Second copy of initial entity diagrams"?

No @holtzmak , it was just there to reference. I wanted to keep everything in one folder.

**Comment by mansiPaTeLL** [comment]
@holtzmak For, 

1. I think you are right about to have one or more relationship entity for ShipperInfo, TransporterInfo, VehicleInfo. I made changes for these. 

2. We will definitely use the auto complete feature, so user doesn't need to enter the information over and over again. 

3. I think we can define custom field formats but I think it may depends on the database and language we are using. I am not sure if I understood your concern here correctly.  

4. The animal group id will remain same for that particular travel document for the same transporter. If another transporter is transporting same animal group on different time, it will be different animal group id as information related to the animal group will be different for that another transporter's travel history document. I hope this makes sense. 

5. So for Company entity, we not giving access to other fields. We are just fetching the data that is required in the form. This will make sense when we actually start working with Database.

**Comment by MummenRider** [comment]
I suggest you to do the following:
- [x] For composite attributes like address and phone numbers, you can create another table and make sure each attribute is atomic. For example: DeliveryAddress(id, province, city, street, etc).
[Here's](https://logicalread.com/sql-server-entity-relationship-model-mc03/#.X_oUY2RKhuU) an article that can help you

**Comment by holtzmak** [comment]
> 3. I think we can define custom field formats but I think it may depends on the database and language we are using. I am not sure if I understood your concern here correctly.

@mansiPaTeLL If this depends on the database and language, then we can just expand your current diagram when we decide on the database to use. Everything else and your above answers LGTM!

**Comment by holtzmak** [comment]
@mansiPaTeLL could you add your PDFs to the codebase under `documentation/database architecture` please?

**Comment by mansiPaTeLL** [comment]
@holtzmak I added a folder and created a pull request. Thanks.
