### ISSUE TITLE
Create our first draft of the Database Interface

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#70]
As per the design in #67 and that we have a specific database type in mind for #69, we should make a generic interface for the different databases that could be used with our software. 

Recall the [Strategy Design Pattern](https://en.wikipedia.org/wiki/Strategy_pattern), we'll want to provide the same pattern in our application so many databases can be used at once with the software. This will help future developers expand our software when picking it up.

Consider the major mobile-interaction databases: SQLite, MariaDB, MongoDB, etc. We'll want an interface that works with the Strategy pattern.

This task is done when:
- [x] An interface is designed that is agnostic for most databases, and referenced in the client-server architecture drawings

**Comment by holtzmak** [comment]
As thought in the client-server architecture design session, we should consider how the local database (saving to the phone) works and if we need a particular interface for it or if Flutter provides it for us.

**Comment by SanaKhan1997** [comment]
Sources used:
1. [Flutter(how to persist data)](https://flutter.dev/docs/cookbook/persistence/sqlite)
2. [Read-Write into database](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_db.md)
3. [Shared Preferences](https://medium.com/flutter-community/how-to-use-local-storage-in-flutter-3169e34f051b)
4. [Data Persistence on Flutter(save into files)](https://www.raywenderlich.com/5965747-data-persistence-on-flutter#toc-anchor-013)

**Comment by holtzmak** [comment]
> Sources used: ...

Perhaps we'll need to start a Flutter Guide wiki page with links like these
