### ISSUE TITLE
Investigate (and design) application settings

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#74]
We've identified that it would be very nice if transporters could stay logged in on subsequent app launches. We need to investigate how Flutter (or the operating system of the phone, etc.) would save application settings when the app is closed.

Some questions to answer:
1. Do we need to program something specifically to do this? If yes, what's the typical way to do this?
1. Does Flutter provide the API for this that we simply interface to? (I think this is most likely) How does the Flutter API guarantee persisting save data?
1. The saving of settings and saving to a local database that persist when the application is closed are very similar things, investigating this settings problem should open the door to how a local database would work.

- [x] Once this problem has been resolved (i.e. we know what to do), add the respective drawings to the client-server architecture. 

In our case, the settings are either part of the mobile app container (standalone) or is part of the mobile client interfacing the GUI.

**Comment by MummenRider** [comment]
This ticket involves 2 kinds of app life cycle, onPause and onResume.
When user minimizes the app, in user's perspective it may look like it's closed but in reality the app is still running. The app will go in onPause state. Once user decided to re-open the app, it'll go to a state called onResume.

1. One way to implement this behavior is to use [WidgetsBindingObserver class](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html). Flutter do not provide an API for this.

2. An alternative is  to save the session is to add a dependency called [FlutterSession](https://pub.dev/packages/flutter_session)

**Comment by holtzmak** [comment]
Should add WidgetBindingObserver class to GUI Architecture drawing when ready (blocked by Hi-fis #55 )

**Comment by MummenRider** [comment]
Additional option to achieve persistent login:

3.) [shared_preference](https://pub.dev/packages/shared_preferences): We can use shared preference by checking if user already logged. The session can be store locally in a String or bool data type. Note that shared preference should not be use to store sensitive information

4.)[Firebase Authentication](https://firebase.flutter.dev/docs/auth/usage/): This method is a lot easier to set up and more secured compared to previous suggestion due to data encryption feature.

**Comment by holtzmak** [comment]
There is no need to update documentation drawings at this time.
