### ISSUE TITLE
Experiment with Flutter GUI

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#78]
Using the project framework set up in #56 , experiment with the following items:
* Make a widget (window)
* Make a sticky navigation bar (a bar that is on all windows/widgets)
* Make a sliding menu (a menu you swipe left/right to show/hide)
* Make our progress bar imitation (think of the circles in the GUI prototypes) (consider how we would update progress)

You're free to play with other GUI elements too, buttons, colors, etc.

Any code you write to do the above can be merged into the codebase - we'll be able to overwrite/copy/etc. when we go to create the final GUI windows/widgets. You may want to keep a list of references that helped you: for example, Flutter cookbook pages - decide if we should have a dedicated wiki page for Flutter cookbook items.

**Comment by MummenRider** [comment]
- [x] Create a Bottom Navigation Bar.  (Note: This task should include creating widgets)
- [x] Create a sliding window
- [ ] Create progress bar (Note: This task may take a lot of time to finish due to its state complexity)

**Comment by MummenRider** [comment]
Creating progress bar would require strong knowledge about state management system which I believe deserve its own issue. I will create a new issue for this in the future.
