### ISSUE TITLE
Experiment with Code Testing in Flutter

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#82]
Using the project framework set up in #56 , experiment with the following items:
* Make a suite of tests that can run automatically (at the click of a button)
* Make and use a mock object in Dart (use a library like Mockito, but for Dart)
* Investigate if Flutter can do system level tests (i.e. once the simulator is running, interact with the GUI and verify events happen)
* Investigate if Flutter can do GUI tests (just the GUI code, like confirming that a button click starts an event)
* If the above two points are easy, write some simple test code

You should use an existing library(s): document what kind of options it provides use with (for example, can it use both android and iOS simulators? Can it mock external systems like databases?)

Any code you write to do the above can be merged into the codebase - we'll be able to overwrite/copy/etc. when we go to create the final GUI windows/widgets. You may want to keep a list of references that helped you: for example, Flutter cookbook pages - decide if we should have a dedicated wiki page for Flutter cookbook items.

**Comment by holtzmak** [comment]
After some investigation, I've found the following exciting things:

* Make a suite of tests that can run automatically (at the click of a button)

This is an easy, common thing to do. If you recall JUnit, the suite of tests were simply several functions in a test class that would run with the JUnit runner from any application with the JUnit plugin (or from command line).

In Flutter, test suites are done with `group`s of `test`s. Again, we can run these tests from an application with the Flutter plugin (or form command line):
```
void main() {
  group('Test Group', () {
    test('test description', () {
      expect(some value a, some value b);
    });
    test('another test description', () {
      // some other check
    });
  });
}
```

* Make and use a mock object in Dart (use a library like Mockito, but for Dart)

Even the Flutter cookbook suggests using Mockito, see [here](https://flutter.dev/docs/cookbook/testing/unit/mocking)! The Mockito library uses the same syntax across languages, there isn't anything new to learn if you're already familiar (besides new Dart syntax for creating objects and such). 

We can use Mockito to mock just about anything, and since our design includes interfaces to external software systems, we can use the interface for mocks without needing to interact with the external systems in the test.

* Investigate if Flutter can do system level tests (i.e. once the simulator is running, interact with the GUI and verify events happen)
* Investigate if Flutter can do GUI tests (just the GUI code, like confirming that a button click starts an event)
* You should use an existing library(s): document what kind of options it provides use with (for example, can it use both android and iOS simulators? Can it mock external systems like databases?)

Yes! The Flutter cookbook describes such "system", GUI-interaction tests as integration tests, see the cookbook example [here](https://flutter.dev/docs/cookbook/testing/integration/introduction).

The way this is done is described as "driving" a running application with instructions to interact with the GUI (like "tapping" buttons), and then using Flutter's internal "search" functions to verify that events occurred. Something to note about event verification - we'll have to "name" observers in order to grab them in tests and check that they've received something - therefore we can also think of Flutter's search as an observer of observers.

We can run driven test on any emulator or real device (would be kinda cool to watch your phone magically do things without you touching it).

Because the integration tests follow the typical test structure, we can chose to use mocks in integration tests. We can use the real, external systems if we set up the emulators to make external connections, and wait for responses in the test. Using the external systems may not be super reliable if they're down, but the mock tests should pass still, so we can identify that external system went down accidentally during the test.

**Comment by holtzmak** [comment]
Some things I can do at this point are:
- [x] Create a system (integration) test with the dummy widgets, etc. we have or will have soon in the codebase
- [x] Similar to above, create a test with the dummy widgets, etc. and use mock objects

 But, these tests would soon be obsolete - I could spend my time elsewhere. What do you think @MummenRider , @mansiPaTeLL ?

**Comment by MummenRider** [comment]
@holtzmak you can definitely create test for the dummy widgets and be familiar how testing works in flutter.

**Comment by holtzmak** [comment]
TODOs from this task:
- [x] Update Flutter Actions to do separately unit tests and builds (remove build action from every push except to master)
- [x] Add Flutter Action for integration tests (will need to specify emulator devices)
- [x] Add one sample suite of integration tests

Will be adding testing instructions in task #100
