### ISSUE TITLE
Experiment with application settings with Flutter

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#83]
Using the project framework set up in #56 , experiment with the following items:
* Make and save application settings to the mobile device Shared Settings (i.e., let's say there's a dark mode setting, have the dark mode toggle button be available in device settings and verify the app can tell what state the toggle is in [on/off]) (this is more code than other experimental tasks)

Any code you write to do the above can be merged into the codebase - we'll be able to overwrite/copy/etc. when we go to create the final GUI windows/widgets. You may want to keep a list of references that helped you: for example, Flutter cookbook pages - decide if we should have a dedicated wiki page for Flutter cookbook items.

**Comment by MummenRider** [comment]
The behavior described in this issue can be achieved by using a plugin called shared preferences.

**Comment by holtzmak** [comment]
@MummenRider What does a plugin mean for Flutter?

**Comment by MummenRider** [comment]
@holtzmak this is something we add in pubspec file. This specific plug in will store small data like preferred settings locally. By doing so, even if user closes the application, our app do not need to interact with our database nor it needs internet to function. I imagine plugin as a blueprint where we can do our own implementation like extending the class or create instances. If you want more explanation about plugin, go to https://flutter.dev/docs/development/packages-and-plugins/developing-packages

**Comment by MummenRider** [comment]
This issue is similar to #74. For more info how to save application settings, please check [shared preferences](https://pub.dev/packages/shared_preferences)
