### ISSUE TITLE
Experiment with the Firebase API

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#95]
Follow-up to #70 but with Firebase. Blocked by #96 (invalid if the task chooses SQlite/AWS)

You should investigate first the work done so far in #70, and see what changes should be made in order to use Firebase. Additionally, some investigation done in #81 could be useful. Speak with the assignees of the two tasks before beginning.

This task is done when:
- [x] You can use/understand how the Firebase API lets us make fetches, updates, and any other notable things you find

**Comment by holtzmak** [comment]
Related to #80 , the VPN/https setting may very well just be an option on Firebase. We should use the VPN/https for Firebase connections, meaning that we should experiment with the Firebase API over VPN/https.

**Comment by MummenRider** [comment]
To start experimenting Firebase API (e.g. CRUD), then I believe we should set up our Firestore db first. I need data I can manipulate for Firebase API testing.  This task being blocked by #130 and (or) #124.
My plan is as follows:
- [x] Re-structure our current application based on this [link](https://www.raywenderlich.com/6373413-state-management-with-provider). 
- [x] Go back to this issue and perform CRUD operation to our mock db

**Comment by holtzmak** [comment]
@MummenRider the mock will just be a mock of the Firebase interface as per #130 . We don't need any sort of test database, the Mockito library allows us to define "on-the-fly" what the database interface would respond with given any query: this is the entry point to the database so we can "stop" there.

This is shown [here, an example of another type of database being mocked](https://flutter.dev/docs/cookbook/testing/unit/mocking). See the `when` calls.

**Comment by MummenRider** [comment]
When I mentioned 'test', I don't mean the testing itself. For lack of a better word I used 'test' 
> @MummenRider the mock will just be a mock of the Firebase interface as per #130 . We don't need any sort of test database, the Mockito library allows us to define "on-the-fly" what the database interface would respond with given any query: this is the entry point to the database so we can "stop" there.
> 
> This is shown [here, an example of another type of database being mocked](https://flutter.dev/docs/cookbook/testing/unit/mocking). See the `when` calls.

**Comment by MummenRider** [comment]
Here are the CRUD operations I'm going to do for this task:
- [x] Create a user
- [x] Retrieve a user info 
- [x] Update user's information 
- [x] Delete a user

Note: For this task, I will create a User model and a collection in Firebase console

**Comment by MummenRider** [comment]
Things I learned during experimentation that I believe worth sharing to @holtzmak, @mansiPaTeLL, @SanaKhan1997 :
- Data/documents in firestore is in JSON format. What this mean to us is we need to have a method that will Serialize data for us. We do this when we want to read data from firestore.
- When passing data to firestore, we then need to deserialize that data/object we want to upload to firestore
- Firestore is different to Realtime database. If we want Firestore to respond to real time changes, then we need to use Stream to continually listen to changes. Note: This is the part I'm currently researching
- Tons of tutorials online are outdated due to recent [Firebase breaking changes](https://firebase.flutter.dev/docs/migration/).

**Comment by holtzmak** [comment]
@MummenRider I make reference to this possible serializer/deserializer in my recent PR #144 .

**Comment by MummenRider** [comment]
I already have methods to do such thing and will be available in my next PR
> @MummenRider I make reference to this possible serializer/deserializer in my recent PR #144 .

**Comment by holtzmak** [comment]
@MummenRider , as discussed: because this task blew up please close it once you have made PRs for the `DialogService and Dialog Manager` and the `Response` type. 

The branch you made will stay open for us to take things from for the other tasks of Sign Up Screen, etc.
