### ISSUE TITLE
Investigate using Firebase over AWS/SQLite

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#96]
It was discovered by @MummenRider and @SanaKhan1997 that Firebase could be a better alternative to AWS/SQLite.

In this task:
- [x] investigate and compare the two options against each other (make a wiki page)
- [x] and compare the two options to the different things we need to do in our application when interacting with the database (saving records, retrieving records, what if the internet connection is down?). Which is less work?

We'll end up using the better option as deemed by this task.

**Comment by mansiPaTeLL** [comment]
@MummenRider @holtzmak @SanaKhan1997 
See this [Wiki](https://github.com/holtzmak/Humane-Transport/wiki/Firebase-vs.-AWS-Amplify)

**Comment by MummenRider** [comment]
> @MummenRider @holtzmak @SanaKhan1997
> See this [Wiki](https://github.com/holtzmak/Humane-Transport/wiki/Firebase-vs.-AWS-Amplify)

Can you give us the sources in the wiki? I want to read more about its offline features

**Comment by mansiPaTeLL** [comment]
@MummenRider Please see the source - https://firebase.google.com/docs/firestore/manage-data/enable-offline

**Comment by SanaKhan1997** [comment]
Just wanted to make sure if you have looked at firebase storage limits, standard limits and security rules. Since, its on cloud there might be limitations on the free firebase version. See this--> [https://firebase.google.com/docs/firestore/quotas](https://firebase.google.com/docs/firestore/quotas)

**Comment by mansiPaTeLL** [comment]
@SanaKhan1997 for development purposes it will be fine. When it goes into production, with an increasing number of users, you may have to pay. This is the same with all cloud services available in the market. See this --> https://blog.back4app.com/aws-amplify-vs-google-firebase/
& https://firebase.google.com/pricing

**Comment by mansiPaTeLL** [comment]
> Just wanted to make sure if you have looked at firebase storage limits, standard limits and security rules. Since, its on cloud there might be limitations on the free firebase version. See this--> https://firebase.google.com/docs/firestore/quotas

Another thing, I want to mention here is we are going to use Firebase Realtime Database. Firestore has different pricing for storage.  Also, they provide another database called Cloud Firestore. Ser this --> https://firebase.google.com/docs/database/rtdb-vs-firestore

For our project requirements, I think Realtime Database will be fine.

**Comment by SanaKhan1997** [comment]
> > Just wanted to make sure if you have looked at firebase storage limits, standard limits and security rules. Since, its on cloud there might be limitations on the free firebase version. See this--> https://firebase.google.com/docs/firestore/quotas
> 
> Another thing, I want to mention here is we are going to use Firebase Realtime Database. Firestore has different pricing for storage. Also, they provide another database called Cloud Firestore. Ser this --> https://firebase.google.com/docs/database/rtdb-vs-firestore
> 
> For our project requirements, I think Realtime Database will be fine.

Thanks for looking into this. What I understand from the above documentation is that cloud firestore is for more complex systems and since both firebase DB(firestore and real-time) have similar features and structure, we can adopt real-time firebase .

**Comment by holtzmak** [comment]
Good to see that we can define security rules, this makes our role-based security provisions more concrete.  Firebase LGTM, especially that the AWS equivalent isn't ready (we dumped KMM for this same reason and it worked good for us).
